version: 2

registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{secrets.NPM_TOKEN}}

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "06:00" # 8:00 Berlin time
    open-pull-requests-limit: 0
    allow:
      - dependency-name: "@zattoo*"
    registries:
      - npm-registry-registry-npmjs-org
    assignees:
      - dependabot
    pull-request-branch-name:
      separator: "-"
