language: node_js
os: linux
node_js:
  13.5.0

branches:
  only:
    - master
    - production
    - release
    - hotfix

stages:
  - test
  - name: publish
    if: (branch = production) AND NOT (type = pull_request)

jobs:
  include:
    - stage: test
      install:
        - npm ci

    - stage: publish
      before_install:
        - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      install:
        - npm ci
        - npm i @zattoo/zploy@1.0.0-rc.0 -g
      script:
        - zploy --gh_token=$GH_TOKEN --npm_token=$NPM_TOKEN

notifications:
  email:
    false
