name: Publish

on:
  push:
    branches:
      - production

jobs:
  publish:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{github.token}}
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm config set //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}
      - uses: zattoo/publish@v1
        with:
          github_token: ${{github.token}}
          npm_token: ${{secrets.NPM_TOKEN}}
