name: Test

on:
  pull_request:
    branches:
      - master
      - production
      - release
      - hotfix

jobs:
  changelog:
    name: Changelog
    if: contains(github.head_ref, 'backmerge') != true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: zattoo/changelog@v1
        with:
          token: ${{github.token}}
  validate-rules:
    name: Validate Rules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install
        run: npm ci
      - name: Lint Styles
        run: npm run test
